### ISSUE TITLE
Fork request: thet/pat-leaflet

### ISSUE THREAD

**Issue by thet** [Patternslib/Patterns#432]
I'm developing a leaflet map pattern (http://leafletjs.com/). I'd like to submit it for the Patternslib organization. If you feel this is appropriate, can someone with the necessary permissions please fork it into the Patternslib organization? /cc @jcbrand @pilz 

https://github.com/thet/pat-leaflet

pat-leaflet isn't fully finished and will likely be extended while developing the project, where we are going to use it. What's missing is:
- more configuration options,
- some more useful plugins,
- tests.

By the way, what's your preferred test framework for patternslib patterns?

There is already a leaflet pattern in your organization, but looks like a pattern done for a specific project with requirements which do not fit for other usecases: https://github.com/Patternslib/pat-map-leaflet

**Comment by jcbrand** [comment]
Done. See here: https://github.com/Patternslib/pat-leaflet

Ideally there would be only one leaflet pattern, but they're both not in the core Patterns repo so it's not a train smash. It would be great however if a clear winner emerges. So, if the other pattern is too specific, it would be great if you could make your pattern as generic and reusable as possible so that it can be used generally.

About tests, we use Jasmine tests for Patterns. We still use Jasmine 1.3 (with a small patch which I added and which wasn't accepted into mainline because they stopped support for 1.3 in favor of 2.x).
The main reason being that they changed lots of semantics in 2.0 and porting will likely be a lot of effort. On top of that, Jasmine 1.3 still works fine for us.

So for tests, I would recommend using the same testing setup, or otherwise to use Jasmine 2.x. If you use other testing frameworks then you make it difficult to impossible to eventually include your pattern in the Patterns core.

Let me know if you need any help with getting the testing infrastructure working.
