### ISSUE TITLE
Bumper update interval

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#437]
Bumpers move rather choppy when the user scrolls. This can be solved with some CSS tricks with position sticky. Except position sticky is only applicable for certain cases and it's taken out recent versions of Chrome again, setting us back to square one. 

Is the smoothness of the bumper related to the interval in which it measures/updates the position? If so could we increase this interval so that bumpers become smooth in all browsers?

**Comment by jcbrand** [comment]
*Looking at the code quickly...*

There is no explicit update interval. The pattern listens to the scroll event and updates whenever that event gets fired, without delay. If the browser fires that event continuously and smoothly, then I would expect the bumper to move smoothly as well.

More investigation would be required to figure out what could be done about the choppiness.

**Comment by jcbrand** [comment]
@cornae I have an idea how we can solve the performance problems, at least for elements that are bumped to the window (i.e. this won't work for elements bumped to a container).

Instead of continuously computing the top of the sticky element relative to it's container and setting the `top` value to a new value, we can instead set `position: fixed;  top: 0;`.

My initial tests show that this removes the flickering and makes the sticky element completely smooth.

However, I want your feedback first on whether it's ok to make the position fixed before I continue on this.

**Comment by cornae** [comment]
That sounds precisely how the old bumper pattern worked. I guess the
problem was that you loose the positioning over the other axes when you
switch to position fixed.

Op za 30 jan. 2016 om 23:55 schreef JC Brand <notifications@github.com>:

**Comment by pilz** [comment]
This sounds as if we can't fix this. Position fixed is not good enough and we don't have a way to control how the scroll event fires. Is this problem perhaps not an issue anymore or perhaps pat-sticky solves it? @cornae, can we close this?

**Comment by cornae** [comment]
Pat sticky solves it in 90% of the cases provided that dynamic class .stuck/.sticking is in place. So far I've worked around it with some black magic.

**Comment by pilz** [comment]
Pareto good enough :)
