### ISSUE TITLE
legend and auto-scale patterns break with used jQuery version

### ISSUE THREAD

**Issue by wichert** [Patternslib/Patterns#536]
The auto-scale and legend patterns use `$.browser` for browser detection. `$.browser` was removed in jQuery 1.9. Patternslib uses jQuery 1.11 (as specified in package.json), so these patterns do not work.

**Comment by pilz** [comment]
We include jquery.browser for compatibility. But I also stumbled over this recently and I wonder whether we need to support these special cases still. Or can we say we don't support these browsers anymore and therefore remove the special case?

I am also all for jQuery 3, because there is another issue where jquery 1.11.3 removes a test whether getElementByClassName is available - and it is not in IE11 on svg elements, so we had to downgrade to 1.11.0 or upgrade to jquery3. 

Do you have a gut feeling how much effort such an upgrade might be? And would you be willing to help in case we run into problems for the core elements like parser?

**Comment by wichert** [comment]
The parser doesn't rely on jQuery that much, so that should be easy to fix. Remove jQuery from all patterns would be a pretty significant effort without too much direct again. I would do that very gradually by just setting a policy that new code should not use jQuery unless there is a real need to.

For getElementsByClassName you can just use `querySelectorAll([null, ...classes].join('.'))`, which should always work.

**Comment by pilz** [comment]
That code is in sizzle which is part of jquery :/

**Comment by pilz** [comment]
We are on JQ3 now, closing
