### ISSUE TITLE
Hooks cannot be parsed

### ISSUE THREAD

**Issue by lucaswiersma** [Patternslib/Patterns#660]
We are tyring to fire an event after succesfull injection to notify our analytics software that the page has reloaded. For this I want to make use of the "hooks option" that the library offers but when I try to set this up I keep getting errors that the parser cannot parse my value for hooks. 

I have tried the following:

data-pat-inject=" hooks: ['hook1'] "
data-pat-inject=" hooks: 'hook1' "
data-pat-inject=" hooks: hook1

The error I get is: 

patterns.inject.parser: Illegal value for hooks: ['hook1'] ( or 'hook1' or hook1)

The only thing that seems to be working is when I set the value to the default value, so 

data-pat-inject=" hooks: raptor

But I cannot add any subsequent hooks with my own name. 

What am I missing or is there a bug in the framework that causes this behaviour

**Comment by pilz** [comment]
We only added the hook feature so that we could trigger raptor to behave. We didn't build a generic mechanism, so I fear that will not help you. Also we don't use raptor anymore, so this feature is abandoned. 

What you could do though is to listen for the pat-update event that is triggered after an injection and if that happens, notify analytics. 

Hope that helps.
