### ISSUE TITLE
Pat inject target value empty

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#690]
Sometimes I need to just post something without the need for displaying feedback. Injecting some result somewhere on the page (like replacing the logo with the logo) just to make it work is dirty. A special value `none` for the property`target` would do the trick.

**Comment by pilz** [comment]
We have quite extensive code ensuring that the target exists. Writing target:none is going to confuse every developer in the future when reading code checking that this is not none (the only difference being the quotes around the 'none').

As we must document this feature anyway, would it be ok to name it 'target:discard' or similar so that it becomes clear that this is a reserved keyword and it means something specific?
@cornae…

**Comment by pilz** [comment]
A first attempt is implemented and pushed to patternslib. Please try if it behaves as you like. 
A test is available at the end of the pat-inject demo page.
