### ISSUE TITLE
Pat scroll and body scroll classes

### ISSUE THREAD

**Issue by cornae** [Patternslib/Patterns#702]
Pat scroll doesn't change the body scroll classes the way user scrolling does. 

The only thing the minimal version of the new scroll detection feature is missing is that pat scroll would also influence the `scroll-position-down/up` body scroll class. 

An ideal version would on top of changing the `scroll-position-down/up` class also add `auto-scroll-position-down/up` for pat-scroll (or other non user) triggered scroll events and `user-scroll-position-down/up` for user triggered scroll events. So in total three classes. This gives maximum flexibility over the behaviour of stick&hide bars.

**Comment by cornae** [comment]
Additionally: The up and down classes also don’t respond to iPad  scroll events and to scrollbar triggered scroll events. Ideally those events would also set the `scroll-position-down/up` class. Anything that makes the page scroll :).

**Comment by pilz** [comment]
The up and down classes should now also respond to ipad scrolls by listening to the touchmove event as well.

For implementing the additional classes for pat-scroll, I need a demo to test and @cornae will give me the same effect of http://stichtinginclusiefjodendom.cornelis.amsterdam also on the syslab website proto

**Comment by thet** [comment]
@cornae @pilz Fixed with https://github.com/Patternslib/Patterns/pull/727
There is a slight change in the behavior: To have the scroll classes automatically set on the body when the window is scrolled, then now you need to add the ``pat-scroll-box`` class to the body.
But since in quaive the window isn't scrolled but the main scrolling happens in ``#portal`` this change shouldn't break anything.
I suggest to not add the ``pat-scroll-box`` to body as it's probably not needed there but only to the ``#portal`` container.

By the way - currently pat-scroll-box checks if the container is scrollable by checking if overflow/y is set to auto/scroll. But we could also add ``.pat-scroll-box { overflow-y: auto; }`` which would make it even simpler to use.

**Comment by cornae** [comment]
Yes I agree. For Quaive I wouldn’t set it on body. For more website-ish project where the entire page scroll I would. 

I might add that to the CSS, but for Quaive in particular the overflow behaviour is tuned for every individual scroll pane, so that won’t be necessary.

**Comment by cornae** [comment]
Fixed by @thet
